"""reserve_flag toegevoegd

Revision ID: 1813153ad9d8
Revises: 4e5e5489a63c
Create Date: 2026-02-06 12:34:57.987359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1813153ad9d8'
down_revision: Union[str, Sequence[str], None] = '4e5e5489a63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('reserve_flag', sa.Boolean(), nullable=True))
    op.add_column(
        "customers",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "is_active")
    op.drop_column("customers", "reserve_flag")
    # ### end Alembic commands ###
